  - name: Install Keystone Ubuntu
    apt:
      name:
        - keystone
        - apache2
        - libapache2-mod-wsgi
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
